###### Main Service ######
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mainservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: main-deployment
    spec:
      containers:
        - name: mainservice-java
          image: mainservice-java:latest
          ports:
            - containerPort: 9080
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: main-service
  namespace: default
spec:
  ports:
    - port: 9080
  selector:
    name: main-deployment
